version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: npm
    directory: /docker
    target-branch: dev
    schedule:
      interval: daily
      time: '02:00'
  - package-ecosystem: docker
    directory: /
    target-branch: hotfix
    schedule:
      interval: daily
      time: '02:00'
