services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    # TO OPEN DATABASE TO HOST
    # ports:
    # - 5432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    build:
      context: .
      args:
        - DB_ADMIN=postgres
        - DB_ADMIN_PASSWORD=password
        - DB_HOST=database
        - DB_PORT=5432
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    volumes:
      - tanatlocData:/root/tanatloc

volumes:
  postgresData:
  tanatlocData:
