services:
  tanatloc:
    build:
      context: .
      args:
        - DB_ADMIN=postgres
        - DB_ADMIN_PASSWORD=password
        - DB_HOST=database
        - DB_PORT=5432
    depends_on:
      - database
      - converters
      - freefem
    ports:
      - '3000:3000'
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    volumes:
      - tanatlocData:/root/tanatloc
      - convertersBin:/root/converters
      - freefemBin:/root/freefem

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - postgresData:/var/lib/postgresql/data

  converters:
    image: tanatloc/converters
    volumes:
      - convertersBin:/root/converters

  freefem:
    image: freefem/freefem
    volumes:
      - freefemBin:/usr/freefem/bin

volumes:
  postgresData:
  tanatlocData:
  convertersBin:
  freefemBin:
