services:
  tanatloc:
    build:
      context: .
      args:
        - DB_ADMIN=postgres
        - DB_ADMIN_PASSWORD=password
        - DB_HOST=database
        - DB_PORT=5432
    depends_on:
      - database
    ports:
      - '3000:3000'
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    volumes:
      - tanatlocData:/root/tanatloc

  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresData:/var/lib/postgresql/data

volumes:
  postgresData:
  tanatlocData:
