services:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    # TO OPEN DATABASE TO HOST
    # ports:
    #   - 5432:5432
    volumes:
      - postgresData:/var/lib/postgresql/data

  tanatloc:
    build:
      context: .
      args:
        - DB_ADMIN=postgres
        - DB_ADMIN_PASSWORD=password
        - DB_HOST=database
        - DB_PORT=5432
        - SOURCE_BRANCH
        - SOURCE_COMMIT
    depends_on:
      - database
    environment:
      - DB_ADMIN=postgres
      - DB_ADMIN_PASSWORD=password
      - DB_HOST=database
      - DB_PORT=5432
    volumes:
      - tanatlocData:/root/tanatloc

  network:
    image: nginx
    depends_on:
      - tanatloc
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

volumes:
  postgresData:
  tanatlocData:
