name: Dispatch

on:
  push:
    branches:
      - master

jobs:
  electron:
    name: Dispatch to tanatloc-electron
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch for electron
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.DISPATCH_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Airthium/tanatloc-electron/actions/workflows/electron.yml/dispatches -d '{"ref": "main"}'

  docker:
    name: Dispatch to tanatloc-docker
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch for docker
        run: echo TODO
