name: Build/release electron

on:
  push:
    branches:
      - master

jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@main
      
      -name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v0.9
          release_name: v0.9
          body: |
            Electron
          draft: false
          prerelease: false

  release:
    name: Build and release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@main

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@main
        with:
          node-version: 16

      - name: Install
        run: yarn install

      - name: Electron build
        run: yarn electron-build
