name: Node
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.SUBMODULES_TOKEN }}
          submodules: recursive

      - uses: actions/setup-node@master
        with:
          node-version: '16.3.0'

      - name: Install
        run: yarn install

      - name: Depcheck
        run: yarn depcheck

      - name: Lint
        run: yarn prettier

      - name: Tests
        run: yarn test || true

      - name: Unsubscribe
        run: yarn next telemetry disable

      - name: Build
        run: yarn build

      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dproject.settings=config/sonar/sonar-project.properties
