name: Node
on: [push]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install
        run: yarn install
      - name: Depcheck
        run: yarn depcheck
      - name: Lint
        run: yarn prettier
      - name: Build
        run: yarn build
      - name: Server build
        run: yarn server-build
      - name: SonarCloud scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
